global:
  scrape_interval: 15s
  scrape_timeout: 10s
  external_labels:
    monitor: async-health-checker

scrape_configs:
  - job_name: async-health-checker
    metrics_path: /metrics
    static_configs:
      - targets:
          - app:8000

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
