"""Initial revision

Revision ID: d8e8328bffdb
Revises: 7fe50aaddb60
Create Date: 2026-08-22 19:12:40.808207

"""
from typing import Sequence, Union

from alembic import op
from database.models.check_results import CheckResults
from database.models.tasks import Tasks
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e8328bffdb'
down_revision: Union[str, Sequence[str], None] = '7fe50aaddb60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'completed', 'failed', name='task_status'), server_default='queued', nullable=False),
    sa.Column('total_urls', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.alter_column('check_results', 'status_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('check_results', 'response_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('check_results', 'error_message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_foreign_key(None, 'check_results', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'check_results', type_='foreignkey')
    op.alter_column('check_results', 'error_message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('check_results', 'response_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('check_results', 'status_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
